#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

const YII_ENV_DEFAULT = 'prod';
const YII_DEBUG_DEFAULT = false;

$yiiDebug = isset($_SERVER['YII_DEBUG']) ? (bool) $_SERVER['YII_DEBUG'] : YII_DEBUG_DEFAULT;
defined('YII_DEBUG') || define('YII_DEBUG', $yiiDebug);

$yiiEnv = isset($_SERVER['YII_ENV']) ? $_SERVER['YII_ENV'] : YII_ENV_DEFAULT;
defined('YII_ENV') || define('YII_ENV', $yiiEnv);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
